### PR TITLE
Enhance reload

### PR DESCRIPTION
**Pull request by igrep**
Sorry, but this pull request is complex: I could make a separate PR for each of the commits.
As the title suggests, the most important change is related to reloading (https://github.com/canalun/brick-break-anywhere/pull/13/commits/e5ead659cf3f13dc71e02c865776f08bf54774f4 and https://github.com/canalun/brick-break-anywhere/pull/13/commits/31f0c7005447b8c8b558a61e2b4f7123e16c2cc5).
See the commit message for details.
Feel free to reject one of them if you don't like. I'll rebase to remove it soon.

### CODE REVIEW

**Comment by igrep** [comment]
Sorry! This change doesn't look working as expected in some cases. Convert back to draft.

**Comment by canalun** [comment]
oh, really!? I was about to approve it just now🤣
Thank you for fixing it!
Looking forward to it, and sorry for my late review.

**Comment by igrep** [comment]
Thank you for reviewing. Fixed with 12c7f5388700581a373decda998a4bffbf957668!
And sorry that my testing after 31f0c7005447b8c8b558a61e2b4f7123e16c2cc5 was incomplete.

**Comment by igrep** [comment]
🙏 Let me remind you because I may be completing a new PR whose commits are added from this branch in a week. The changes don't actually depend on this PR, but include a conflict.

**Comment by canalun** [comment]
@igrep 
sorry, I kept you waiting...! I'm reviewing it tonight, got it!

**Comment by canalun** [comment]
Thank you for patience and contribution!

**Pull request merged**
